// <auto-generated />
using IReckonUAssignment.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IReckonUAssignment.DataAccessLayer.Migrations
{
    [DbContext(typeof(ArticleSqlContext))]
    [Migration("20190408003824_CreateArticleDBSQL")]
    partial class CreateArticleDBSQL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IReckonUAssignment.DataAccessLayer.ArticleEntity", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArtikelCode");

                    b.Property<string>("Color");

                    b.Property<string>("ColorCode");

                    b.Property<string>("DeliveredIn");

                    b.Property<string>("Description");

                    b.Property<decimal>("DiscountPrice");

                    b.Property<decimal>("Price");

                    b.Property<string>("Q1");

                    b.Property<int>("Size");

                    b.HasKey("Key");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
